Option Explicit
Dim WshShell, FSO, base, logDir, backendLog, frontendLog, startupLog, backendCmd, frontendCmd
Set WshShell = CreateObject("WScript.Shell")
Set FSO = CreateObject("Scripting.FileSystemObject")

base = "D:\work\other\TaskDog"
logDir = base & "\logs"
backendLog = logDir & "\backend.log"
frontendLog = logDir & "\frontend.log"
startupLog = logDir & "\startup.log"
backendCmd = logDir & "\run_backend.cmd"
frontendCmd = logDir & "\run_frontend.cmd"

If Not FSO.FolderExists(logDir) Then FSO.CreateFolder(logDir)

' 工具：覆盖写入/追加写入
Sub WriteText(p, t)
  Dim ts: Set ts = FSO.CreateTextFile(p, True)
  ts.Write t
  ts.Close
End Sub
Sub AppendText(p, t)
  Dim ts: Set ts = FSO.OpenTextFile(p, 8, True)
  ts.Write t
  ts.Close
End Sub

' 初始化日志头
WriteText backendLog, "=== TaskDog Backend Log (start " & Now & ") ===" & vbCrLf
WriteText frontendLog, "=== TaskDog Frontend Log (start " & Now & ") ===" & vbCrLf
AppendText startupLog, "=== TaskDog Startup (" & Now & ") ===" & vbCrLf
AppendText startupLog, "[hint] Frontend: http://127.0.0.1:3000/" & vbCrLf
AppendText startupLog, "[hint] Backend:  http://127.0.0.1:3001/health" & vbCrLf

' 生成后端启动脚本（隐藏运行，不弹窗）
Dim backendCmdContent
backendCmdContent = "@echo off" & vbCrLf _
  & "cd /d """ & base & "\backend""" & vbCrLf _
  & "if not exist node_modules (" & vbCrLf _
  & "  echo [backend] installing deps...>>""" & backendLog & """" & vbCrLf _
  & "  npm install --loglevel=error >>""" & backendLog & """ 2>>&1" & vbCrLf _
  & ")" & vbCrLf _
  & "echo [backend] starting...>>""" & backendLog & """" & vbCrLf _
  & "npm run dev >>""" & backendLog & """ 2>>&1" & vbCrLf
WriteText backendCmd, backendCmdContent

' 生成前端启动脚本（隐藏运行，不弹窗）
Dim frontendCmdContent
frontendCmdContent = "@echo off" & vbCrLf _
  & "cd /d """ & base & "\frontend""" & vbCrLf _
  & "if not exist node_modules (" & vbCrLf _
  & "  echo [frontend] installing deps...>>""" & frontendLog & """" & vbCrLf _
  & "  npm install --loglevel=error >>""" & frontendLog & """ 2>>&1" & vbCrLf _
  & ")" & vbCrLf _
  & "echo [frontend] starting...>>""" & frontendLog & """" & vbCrLf _
  & "npm run dev >>""" & frontendLog & """ 2>>&1" & vbCrLf
WriteText frontendCmd, frontendCmdContent

' 启动（隐藏）
WshShell.Run "cmd.exe /c """ & backendCmd & """", 0, False
AppendText startupLog, "[spawn] backend npm run dev (hidden)" & vbCrLf

WScript.Sleep 1500

WshShell.Run "cmd.exe /c """ & frontendCmd & """", 0, False
AppendText startupLog, "[spawn] frontend npm run dev (hidden)" & vbCrLf

' 简单健康检查：写入临时 ps1 并执行
WScript.Sleep 8000
Dim ps1, psContent
ps1 = logDir & "\startup_check.ps1"
psContent = "# Auto-generated by start_hidden.vbs" & vbCrLf _
  & "$backend='[check] backend: ';" & vbCrLf _
  & "try { $r = Invoke-WebRequest 'http://127.0.0.1:3001/health' -UseBasicParsing -TimeoutSec 5;" _
  & " if ($r.StatusCode -eq 200) { $backend += 'OK' } else { $backend += 'HTTP ' + $r.StatusCode } }" & vbCrLf _
  & "catch { $backend += 'FAIL: ' + $_.Exception.Message }" & vbCrLf _
  & "$backend | Out-File -Encoding utf8 -Append '" & startupLog & "'" & vbCrLf _
  & "$frontend='[check] frontend: ';" & vbCrLf _
  & "try { $r = Invoke-WebRequest 'http://127.0.0.1:3000/' -UseBasicParsing -TimeoutSec 5;" _
  & " if ($r.StatusCode -eq 200) { $frontend += 'OK' } else { $frontend += 'HTTP ' + $r.StatusCode } }" & vbCrLf _
  & "catch { $frontend += 'FAIL: ' + $_.Exception.Message }" & vbCrLf _
  & "$frontend | Out-File -Encoding utf8 -Append '" & startupLog & "'" & vbCrLf
WriteText ps1, psContent
WshShell.Run "powershell -NoProfile -ExecutionPolicy Bypass -File """ & ps1 & """", 0, True

AppendText startupLog, "[hint] Logs: " & logDir & vbCrLf

' 可选：清理临时文件
On Error Resume Next
FSO.DeleteFile ps1, True
On Error GoTo 0

WScript.Quit